### ISSUE TITLE
DataStore fails sync with Validation error of type FieldUndefined: Field 'syncLessons' in type 'Query'

### ISSUE THREAD

**Issue by jonatantibarovsky** [aws-amplify/amplify-category-api#1309]
### How did you install the Amplify CLI?

nom

### If applicable, what version of Node.js are you using?

v18.7.0

### Amplify CLI Version

10.5.2

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I am getting a sync error after enabling DataStore in my amplify project. 
The sync queries which are supposed to appear in app sync don't get generated when I'm on amplify GraphQL v2, but if I enable datastore on a different environment which is still on GraphQL v1 there is no issue. 
This started happening after migrating the api from v1 to v2.

I've enabled conflict detection in my GraphQL api, set it to auto-merge.

Here is a screenshoot of the errors.

<img width="1002" alt="Screenshot 2023-02-27 at 15 41 08" src="https://user-images.githubusercontent.com/33101763/221802066-0ccf7366-cf63-4635-a7b9-add16aa56ff4.png">

Important to note that none of the models that I have in my schema have a sync query generated for it.

There is only one sync query generated which is syncCollectionWorkouts which is coming from a many-to-many relationship.

`type Collection
@model(queries: {get: "getCollectionById", list: "getAllCollections"})
@auth(rules: [
{allow: private operations: [read]}
])
{
id: ID! @PrimaryKey
name: String
workouts: [Workout] @manytomany(relationName: "CollectionWorkouts")
}

type Workout
@model(queries: {get: "getWorkoutById", list: "getAllWorkouts"})
{
id: ID! @PrimaryKey
name: String!
collections: [Collection] @manytomany(relationName: "CollectionWorkouts")
}
`

### Expected behavior

Expecting to have the sync queries shown on app sync.

### Reproduction steps

amplify update api
enable conflict detection
amplify push

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hi @jonatantibarovsky 👋, Thanks for raising this issue. We are working on reproducing the issue. Could you please run below command and send us the report?
 "amplify diagnose --send-report". 
Please refer [here](https://docs.amplify.aws/cli/reference/diagnose/) for diagnose instructions.

**Comment by AnilMaktala** [comment]
Hi @jonatantibarovsky, Are you currently encountering this problem? If so, could you kindly provide us with the diagnostic report?

**Comment by AnilMaktala** [comment]
Hi @jonatantibarovsky 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!
